### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by AleBut** [meepen/salien-bot#115]
I get this message after running the headless for a few hours:

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request.response [as _callback] (C:\Users\Administrator\Desktop\salien-bot-master\headless\jquery_node.js:78:26)
    at Request.self.callback (C:\Users\Administrator\Desktop\salien-bot-master\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\Administrator\Desktop\salien-bot-master\node_modules\request\request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\Administrator\Desktop\salien-bot-master\node_modules\request\request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)

**Comment by IonBazan** [comment]
@AleBut This should have been logged like `failed url <the url>` by the line above. Do you have such entry in your logs?

**Comment by meepen** [comment]
you are most likely using an older version as this was fixed in another version

**Comment by meepen** [comment]
18d3d6d746ad010b7e1d3

**Comment by AleBut** [comment]
@IonBazan I don't think so.

@meepen Thanks! I was using a 12-13 hours old version
