### ISSUE TITLE
UnhandledPromiseRejectionWarning in headless.js version 1.2.2

### ISSUE THREAD

**Issue by csis0247** [meepen/salien-bot#124]
```
~/salien-bot-master$ node headless
(node:4262) UnhandledPromiseRejectionWarning: TypeError: jar.setCookie is not a function
    at Object.ajax (/home/osboxes/saliens/salien-bot-master-deep2/headless/jquery_node.js:106:9)
    at module.exports.CServerInterface.CServerInterface.GetPlayerInfo (/home/osboxes/saliens/salien-bot-master-deep2/headless/network.js:88:6)
    at GetPlayerInfo.res (/home/osboxes/saliens/salien-bot-master-deep2/headless.js:136:22)
    at new Promise (<anonymous>)
    at Client.GetPlayerInfo (/home/osboxes/saliens/salien-bot-master-deep2/headless.js:135:16)
    at Connect.res (/home/osboxes/saliens/salien-bot-master-deep2/headless.js:77:18)
    at new Promise (<anonymous>)
    at Client.Connect (/home/osboxes/saliens/salien-bot-master-deep2/headless.js:76:16)
    at Object.<anonymous> (/home/osboxes/saliens/salien-bot-master-deep2/headless.js:453:4)
    at Module._compile (module.js:652:30)
(node:4262) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:4262) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Despite being a warning, the expected interface (Running for... Current level... Exp since start...) is also gone.

Using node v8.10.0 on Ubuntu 18.04

**Comment by csis0247** [comment]
Oh sorry my fault! Forgot to npm install after updating the script version.
