### ISSUE TITLE
Not sure what's going wrong here...

### ISSUE THREAD

**Issue by Leotrak** [meepen/salien-bot#127]
Soooo, tried installing the thingy according to the posted guide for the headless version, and I keep getting this when I try to run the application... Any hints or ideas on what I'm doing wrong?

undefined:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (E:\Everything Else\Small Games\nodejs\salien-bot-master\headless.js:67:23)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

**Comment by EoD** [comment]
Did you run `npm install`? Did you copy the token as described into `gettoken.json`?

**Comment by meepen** [comment]
`gettoken.json` doesn't exist

**Comment by meepen** [comment]
or has the wrong values.

**Comment by Adenser** [comment]
if it wouldnt exist there would be a error like this 
![image](https://user-images.githubusercontent.com/39248856/41823637-6b108f6c-7803-11e8-9f04-832d4b03dd41.png)

**Comment by Frederic94500** [comment]
Me too I have a strange problem:

```
SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
```

**Comment by meepen** [comment]
@Frederic94500 that's another issue entirely. it's caused by an older version of node. i will add support for it.

**Comment by meepen** [comment]
Yes, your gettoken.json has the wrong values. Make sure to copy everything from the gettoken link into that file.
