### ISSUE TITLE
TypeError: ajax_object.nosucc is not a function

### ISSUE THREAD

**Issue by GitSeal** [meepen/salien-bot#71]
C:\Users\Administrator\Desktop\salien-bot-master - vijay deena nath chauhan>node headless.js
Running for:      10144 seconds
Current level:    8 (370290 / 450000)
Exp since start:  115200
Estimated exp/hr: 75130
Current planet:   Behind the Screen Planet [41.03%] (id 6)
Current zone:     (2, 6) (id: 74) difficulty: medium
Round time left:  -153 seconds
Next level up:    2018-6-23 16:47:26
failed url https://community.steam-api.com/IMiniGameService/LeaveGame/v0001/, retrying 2
C:\Users\Administrator\Desktop\salien-bot-master - vijay deena nath chauhan\headless\jquery_node.js:70
                ajax_object.nosucc();
                            ^

TypeError: ajax_object.nosucc is not a function
    at Request.response [as _callback] (C:\Users\Administrator\Desktop\salien-bot-master - vijay deena nath chauhan\headless\jquery_node.js:70:29)
    at self.callback (C:\Users\Administrator\Desktop\salien-bot-master - vijay deena nath chauhan\node_modules\request\request.js:185:22)
    at Request.emit (events.js:180:13)
    at ClientRequest.<anonymous> (C:\Users\Administrator\Desktop\salien-bot-master - vijay deena nath chauhan\node_modules\request\request.js:815:16)
    at Object.onceWrapper (events.js:272:13)
    at ClientRequest.emit (events.js:180:13)
    at TLSSocket.emitTimeout (_http_client.js:703:34)
    at Object.onceWrapper (events.js:272:13)
    at TLSSocket.emit (events.js:180:13)
    at TLSSocket.Socket._onTimeout (net.js:396:8)

C:\Users\Administrator\Desktop\salien-bot-master - vijay deena nath chauhan>

**Comment by AleBut** [comment]
I had the same issue. 
I don't know if it's related but I can't get any XP anymore after relaunching.

**Comment by nemesis19782** [comment]
Same here. After restarting, i've tried to use a bot account i have, and it doesn't add experience too

**Comment by GitSeal** [comment]
issue fixed by manual relaunch but i am worry what happen if issue occur while sleep

**Comment by GitSeal** [comment]
hello bro meepen your efforts are strong to community can you create a virtual private server for idling salien, most of members are ready to pay

**Comment by meepen** [comment]
i believe i've fixed this, reopen if this is still an issue. i'm not sure what else i've not added an error function to yet.
