### ISSUE TITLE
SyntaxError: Block-scoped declarations

### ISSUE THREAD

**Issue by Frederic94500** [meepen/salien-bot#92]
Hello!

When I execute the headless script in my Raspberry Pi, there is an error:

```
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
```

**Comment by Frederic94500** [comment]
That's works! 
Thanks!
I think you can put this in `headless.js` and `jquery_node.js`

**Comment by Francis-Hsu** [comment]
`node` on Raspbian Stretch is 4.8.x I think, you may use [`nvm`](https://github.com/creationix/nvm) to get the latest version.
